var Names = {
     //test
    NamesAstartes:
        ['Zadkiel'	,
        'Orphamiel'	,
        'Sachael'	,
        'Quilanus Tacus'	,
        'Cassiuleus Tarivius'	,
        'Baberos Sicarion'	,
        'Lukayden Skulldust'	,
        'Darnar Hammercaller'	,
        'Karrin Silverwalker'	,
        'Mardan Morexus'	,
        'Beliaviton Blai'	,
        'Yarordan Grenzev'	,
        'Sabathiel'	,
        'Satqiel'	,
        'Naaririel'	,
        'Nelereas Ventatys'	,
        'Dariurus Tala'	,
        'Ignadius Coras'	,
        'Kregyrll Doombreaker'	,
        'Drumoth Boulderhorn'	,
        'Gymulf Stonemantle'	,
        'Jardan Grenzar'	,
        'Marqorah Neoterro'	,
        'Cyfen Elgius'	,
        'Kemuel'	,
        'Bethuel'	,
        'Mihael'	,
        'Titumos Vibiucus'	,
        'Alerbus Scagistus'	,
        'Salinus Cyburicus'	,
        'Talbaidin Hellborn'	,
        'Drumict Hellfall'	,
        'Ereon Icehammer'	,
        'Zartagrim Wyrderus'	,
        'Lazerica Darsantar'	,
        'Szorqol Ferrasi'	,
        'Aphael'	,
        'Baruchiel'	,
        'Azriel'	,
        'Tryrthus Cybuntanus'	,
        'Rammiullios Ortycles'	,
        'Northus Beros'	,
        'Orak Dragonbreaker'	,
        'Esdros Deathborn'	,
        'Bulvick Thunderbreaker'	,
        'Amaro Taross'	,
        'Antamech Grenzurus'	,
        'Zhrulemy Domuebus'	,
        'Uzziel'	,
        'Diniel'	,
        'Karael'	,
        'Neleddeus Ticos'	,
        'Consuleus Cassiussius'	,
        'Merolinus Cycus'	,
        'Aegine Fellfist'	,
        'Rakmian Firehammer'	,
        'Ansgion Rockbrow'	,
        'Scamanid Nan'	,
        'Bekar Guillios'	,
        'Krleo Morviar'	,
        'Uriel'	,
        'Cassiel'	,
        'Ezekiel'	,
        'Lazassus Manutys'	,
        'Enovius Issos'	,
        'Thapheus Moncus'	,
        'Kjer Skullscream'	,
        'Benedict Blueborn'	,
        'Seydyn Firefall'	,
        'Varapito Ratica'	,
        'Agavar Fures'	,
        'Lazetrok Morerus'	,
        'Kemuel'	,
        'Raziel'	,
        'Saniel'	,
        'Axalicanus Vibiullis'	,
        'Epildus Ventaris'	,
        'Ignarpheus Orioncus'	,
        'Kriak Dragonslain'	,
        'Rynom Ragemane'	,
        'Esdral Frosthair'	,
        'Scibdek Blayon'	,
        'Tar chia Engef'	,
        'Alego Tarerec'	,
        'Sariel'	,
        'Baradiel'	,
        'Sealtiel'	,
        'Epitrius Morrericus'	,
        'Diomedes Issolux'	,
        'Coriomedes Beruris'	,
        'Ashoec Steelbleeder'	,
        'Henghab Dragonhanded'	,
        'Krian Ashblade'	,
        'Scamartath Engius'	,
        'Rohiryon Phorius'	,
        'Romoveren Guillixx'	,
        'Anpiel'	,
        'Dalquiel'	,
        'Rikbiel'	,
        'Gordialis Aquikios'	,
        'Lullian Aquis'	,
        'Perantinus Ventadexus'	,
        'Grivnart Helltooth'	,
        'Haldrismund Skullsword'	,
        'Toband Stonefisted'	,
        'Zustion Gius'	,
        'Beliadriik Cist'	,
        'Nykosan Cybez'	,
        'Germael'	,
        'Usiel'	,
        'Azrael'	,
        'Titullius Medelaris'	,
        'Jullenus Kyrarus'	,
        'Leonadrios Pholaris'	,
        'Trajek Daggerhammer'	,
        'Holdaidin Icemane'	,
        'Gunnab Darkfisted'	,
        'Aubor Nentre'	,
        'Botaron Gan'	,
        'Szoshan Domios'	,
        'Morael'	,
        'Remiel'	,
        'Hadramiel'	,
        'Thractus Moctus'	,
        'Boreavius Oriorius'	,
        'Avutio Cacos'	,
        'Cadmem Strongfury'	,
        'Haakos Rockhair'	,
        'Orard Ironcrusher'	,
        'Curian Tigova'	,
        'Angebor Trelis'	,
        'Nemellion Cybica'	,
        'Barakiel'	,
        'Karael'	,
        'Ambriel'	,
        'Consupheus Vibiuros'	,
        'Milis Trismecus'	,
        'Tharthus Fabritanus'	,
        'Neodied Steelmoon'	,
        'Ashecht Deadhair'	,
        'Heinmac Skullsword'	,
        'Venacaon Thar'	,
        'Szokona Rubox'	,
        'Mercaevech Grenzuil'	,
        'Sarandiel'	,
        'Razael'	,
        'Gabriel'	,
        'Manduscios Centanus'	,
        'Atades Tibectus'	,
        'Daemion Akiobius'	,
        'Actath Hammerblade'	,
        'Alerath Goreblade'	,
        'Arjaar Strongfisted'	,
        'Skarrox Vikus'	,
        'Gauivech Phiam'	,
        'Skashan Abox'	,
        'Perpetiel'	,
        'Jeremiel'	,
        'Stadiel'	,
        'Tiredis Vibiula'	,
        'Arcalos Medelis'	,
        'Pellaberos Podon'	,
        'Varrinvar Boulderslain'	,
        'Hervah Deadblade'	,
        'Bannund Skullbrow'	,
        'Bray lkca Darez'	,
        'Azkaeslan Hare'	,
        'Auriah Ushai'	,
        'Dalquiel'	,
        'Barchiel'	,
        'Dabriel'	,
        'Hyron Mebius'	,
        'Ferruron Fabriro'	,
        'Hactus Tyrian'	,
        'Benedaar Bloodborn'	,
        'Sieferin Ashwalker'	,
        'Seydon Stormsword'	,
        'Agarqol Kantiam'	,
        'Shen kim Berova'	,
        'Agandian Tibantar'	,
        'Nahaliel'	,
        'Araquiel'	,
        'Zazriel'	,
        'Gordiaptus Stroyus'	,
        'Grimarex Motus'	,
        'Condus Morrellis'	,
        'Grolulf Frostmaw'	,
        'Eadwald Ghostblade'	,
        'Hwygach Hammermoon'	,
        'Carlan Hestuila'	,
        'Amasan Fein'	,
        'Amaro Fantar'	,
        ],
}   


module.exports = Names;
